# Generated by Django 4.0.4 on 2022-05-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='book', on_delete=django.db.models.deletion.CASCADE, related_name='book', to='products.category'),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='category',
            field=models.ForeignKey(default='grocery', on_delete=django.db.models.deletion.CASCADE, related_name='grocery', to='products.category'),
        ),
    ]
